---

- hosts:
        servers
 

  tasks:
          - name: install epel-repo if RHEL or CENTOS
            yum:
                    name: epel-release
                    state: present
            when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
     
          - name: install nginx
            package:
                    name: nginx
                    state: latest
            tags:
                   - install

          - name: start nginx
            service:
                    name: nginx
                    state: started
            tags:
                   - start
          - name: stop nginx
            service:
                    name: nginx
                    state: stopped
            tags:
                    - stop
          - name: start nginx on boot
            service:
                    name: nginx
                    enabled: yes
            tags:
                    - enable
          - name: remove nginx from start on boot
            service:
                    name: nginx
                    enabled: no
            tags:
                    - disable

                 




