---

- hosts:
        servers
  tasks:
  - name: install archive + nano
    package:
      name: "{{ item }}"
      state: latest
    loop:
      - zip
      - unzip
      - gzip
      - nano
  - name: remove unzip
    package:
       name: unzip
       state: absent
  - name: remove nano
    package:
       name: nano
       state: absent

